# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Manual IPFS Deploy

on:
  push:
    branches: [ "manual-ipfs" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'manual-ipfs'
    - name: Use LTS Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm install
    - name: Build Gatsby site
      run: npm run clean && npm run build
      env:
        BASE_URL: "https://hobbyistcs.lemontea.letz.dev/"
        API_ROOT: "/hal/api/v0/"
        DOC_ROOT: "/doc/v0/"
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: site
        path: public/
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: site
        path: public/
    - name: Use LTS Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - shell: bash
      env:
        DYNV6_TOKEN: ${{ secrets.DYNV6_TOKEN }}
        DYNV6_ZONEID: ${{ secrets.DYNV6_ZONEID }}
        DYNV6_RECORDID: ${{ secrets.DYNV6_RECORDID }}
      run: |
        ipfshash=$(npx ipfs-deploy public/ -C -O -p infura)
        echo "ipfs-deploy returned: $ipfshash"
        curl -X PATCH "https://dynv6.com/api/v2/zones/$DYNV6_ZONEID/records/$DYNV6_RECORDID" \
        -H "Authorization: Bearer $DYNV6_TOKEN" -H "Accept: application/json" -H "Content-Type: application/json" \
        -d "{\"data\":\"dnslink=/ipfs/$ipfshash\"}"
