# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Manual IPFS Deploy

on:
  push:
    branches: [ "manual-ipfs" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'manual-ipfs'
    - name: Use LTS Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm install
    - name: Build Gatsby site
      run: npm run clean && npm run build
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: site
        path: public/
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: site
    - name: Use LTS Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - shell: bash
      run: |
        result=$(npx ipfs-deploy public/ -C -O -p infura)
        echo "node returned: $result"
